services:

  spring:
    container_name: spring
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
    networks:
      - ticker-network
    command: >
      /wait-for-it.sh mysql:3306 --timeout=30 --strict -- 
      java -jar build/libs/backend.jar


  vue:
    container_name: vue
    build:
      context: ./frontend
    ports:
      - "5173:5173"   # dev 서버 사용 시
      # - "5173:80"   # 프로덕션(Nginx) 사용 시
    networks:
      - ticker-network

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    networks:
      - ticker-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - ticker-network

volumes:
  mysql-data:
  redis-data:

networks:
  ticker-network:
